### PR TITLE
Add allowed Unicode characters to `identifier`

### PR DESCRIPTION
**Pull request by valentinegb**
Allowed Unicode characters are defined [here](https://groovy-lang.org/syntax.html#_normal_identifiers).

### CODE REVIEW

**Comment by Decodetalkers** [comment]
ci is down, you need to use pretty to format the code

**Comment by valentinegb** [comment]
Hmm, CI's still failing but running `npm run lint` on my machine shows no errors

**Comment by Decodetalkers** [comment]
I do not know what happened. let me do it for you,

**Comment by Decodetalkers** [comment]
ok, I merge it now, thanks for your effort

**Pull request closed without merging**
