### PR TITLE
feat: Support for multiline comments.

### PR DESCRIPTION
**Pull request by run2cmd**
Ability to treat `/* ... */` java like comments as comments in Tree-Sitter. This follows multiline comment and groovydoc. See http://groovy-lang.org/syntax.html#_multiline_comment.

### CODE REVIEW

**Comment by Decodetalkers** [comment]
add some test please.. Thanks

sorry, lint check is failed

**Comment by Decodetalkers** [comment]
The check use https://github.com/Decodetalkers/tree-sitter-groovy/blob/master/package.json#L7 pretty to lint, so just make format the ci will be fine

**Comment by run2cmd** [comment]
@Decodetalkers added tests and fixed lint.

**Comment by Decodetalkers** [comment]
LGTM! Then can you help me update the new hight sheme to nvim-treesitter?

**Comment by run2cmd** [comment]
Sure. Just opened: https://github.com/nvim-treesitter/nvim-treesitter/pull/5076

**Pull request merged**
